@if($section->layout==='hero')
<section class="hero container"><div class="hero-copy"><span class="eyebrow"><span class="short-line"></span>{{ $section->eyebrow }}</span><h1>{{ $section->title }}</h1><p>{{ $section->description }}</p>@if($section->button_label)<a class="button" href="{{ url($section->button_url) }}">{{ $section->button_label }} <span>↗</span></a>@endif<div class="hero-assurance"><span>Company-led analysis</span><span>Clear risks and assumptions</span></div></div><div class="research-cover"><div class="cover-top"><span>STOCKEDGE / RESEARCH DESK</span><span>{{ now()->format('Y') }}</span></div><div class="cover-middle"><span>01 — COMPANY RESEARCH</span><h2>Start with<br>the business.</h2><div class="cover-rule"></div><p>A framework for understanding quality,<br>valuation and what could change.</p></div><div class="cover-bottom"><span>{{ count(config('stockedge.categories')) }} research collections</span><a href="{{ route('research') }}">Browse the library ↗</a></div></div></section>
@elseif($section->layout==='research')
<section class="section container">@include('components.section-heading')<div class="reports-grid home-reports">@forelse($reports->take($section->item_limit) as $report)<x-report-card :report="$report"/>@empty<p>New company research will appear here when published.</p>@endforelse</div></section>
@elseif($section->layout==='market')
<section class="market-section"><div class="container section market-layout"><div class="market-intro"><span class="eyebrow">{{ $section->eyebrow }}</span><h2>{{ $section->title }}</h2><p>{{ $section->description }}</p>@if($section->button_label)<a class="button outline" href="{{ url($section->button_url) }}">{{ $section->button_label }} ↗</a>@endif<div class="snapshot-note"><span class="dot"></span>Illustrative snapshot prices · AUD</div></div><div class="market-table-wrap"><div class="table-title"><h3>Coverage universe</h3><span class="tag">Demo data</span></div><div class="table-scroll"><table><thead><tr><th>Company</th><th>Price</th><th>Change</th><th></th></tr></thead><tbody>@foreach($stocks->take($section->item_limit) as $stock)<tr><td><a class="stock-cell" href="{{ route('stock',$stock->symbol) }}"><span class="company-icon {{ strtolower($stock->symbol) }}">{{ substr($stock->symbol,0,1) }}</span><span><b>{{ $stock->symbol }}</b><small>{{ $stock->name }}</small></span></a></td><td>${{ number_format($stock->price,2) }}</td><td class="{{ $stock->change>=0?'positive':'negative' }}">{{ $stock->change>=0?'+':'' }}{{ $stock->change }}%</td><td><a href="{{ route('stock',$stock->symbol) }}" aria-label="Read about {{ $stock->name }}">↗</a></td></tr>@endforeach</tbody></table></div></div></div></section>
@elseif($section->layout==='collections')
<section class="section container">@include('components.section-heading')<div class="collection-grid">@foreach($collections->take($section->item_limit) as $collection)<a class="collection-card" href="{{ route('research',['category'=>$collection->name]) }}"><span class="collection-number">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $collection->name }}</h3><p>{{ $collection->description }}</p><span class="round-arrow">↗</span></a>@endforeach</div></section>
@elseif($section->layout==='tools')
<section class="tools-section container"><div><span class="eyebrow">{{ $section->eyebrow }}</span><h2>{{ $section->title }}</h2><p>{{ $section->description }}</p>@if($section->button_label)<a class="button light" href="{{ url($section->button_url) }}">{{ $section->button_label }} ↗</a>@endif</div><div class="tool-cards"><a href="{{ route('account','portfolio') }}"><span>01</span><div><h3>Portfolio tracker</h3><p>Review positions and unrealised gains or losses.</p></div><b>↗</b></a><a href="{{ route('account','watchlist') }}"><span>02</span><div><h3>Personal watchlist</h3><p>Keep companies and price thresholds in one place.</p></div><b>↗</b></a><a href="{{ route('page','retirement') }}"><span>03</span><div><h3>Retirement scenario</h3><p>Explore the maths behind a long-term savings plan.</p></div><b>↗</b></a></div></section>
@elseif($section->layout==='editorial')
<section class="section container">@include('components.section-heading')<div class="articles-grid">@foreach($articles->take($section->item_limit) as $article)<x-article-card :article="$article"/>@endforeach</div></section>
@elseif($section->layout==='callout')
<section class="cta-section container"><span class="eyebrow">{{ $section->eyebrow }}</span><h2>{{ $section->title }}</h2><p>{{ $section->description }}</p>@if($section->button_label)<a class="button" href="{{ url($section->button_url) }}">{{ $section->button_label }} ↗</a>@endif</section>
@else
<section class="section container cms-text-section {{ $section->image_path?'with-image':'' }}"><div><span class="eyebrow">{{ $section->eyebrow }}</span><h2>{{ $section->title }}</h2><p class="cms-preserve">{{ $section->description }}</p>@if($section->button_label)<a class="button outline" href="{{ url($section->button_url) }}">{{ $section->button_label }} ↗</a>@endif</div>@if($section->image_path)<img src="{{ route('media.file',basename($section->image_path)) }}" alt="{{ $section->image_alt }}" loading="lazy">@endif</section>
@endif