@extends('layouts.app')
@section('title',ucfirst($tab))
@section('content')
<section class="container account-layout"><aside class="account-nav"><span class="eyebrow">YOUR WORKSPACE</span><h3>{{ auth()->user()->name }}</h3>@foreach(['dashboard'=>'Overview','portfolio'=>'Portfolio','watchlist'=>'Watchlist','subscription'=>'Membership'] as $key=>$label)<a @class(['selected'=>$tab===$key]) href="{{ $key==='dashboard'?route('dashboard'):route('account',$key) }}">{{ $label }} <span>↗</span></a>@endforeach<a href="{{ route('research') }}">Research library ↗</a>@can('admin')<a href="{{ route('admin') }}">Admin studio ↗</a>@endcan<form method="post" action="{{ route('logout') }}">@csrf<button class="link-button">Log out →</button></form></aside><div class="account-main"><span class="eyebrow">A CONNECTED VIEW</span><h1>{{ ['dashboard'=>'Welcome to your edge.','portfolio'=>'Your portfolio. In perspective.','watchlist'=>'Keep your curiosity close.','subscription'=>'Your membership.'][$tab] }}</h1><p class="muted">Your private workspace · All valuations use illustrative demo prices.</p>
@php($value=$holdings->sum(fn($h)=>$h->quantity*$h->price))
@php($cost=$holdings->sum(fn($h)=>$h->quantity*$h->buy_price))
@if(in_array($tab,['dashboard','portfolio']))<div class="metric-grid three"><div class="metric"><small>Portfolio value</small><strong>${{ number_format($value,2) }}</strong></div><div class="metric"><small>Unrealised gain / loss</small><strong class="{{ $value-$cost>=0?'positive':'negative' }}">${{ number_format($value-$cost,2) }}</strong></div><div class="metric"><small>{{ $tab==='dashboard'?'Companies on watchlist':'Invested capital' }}</small><strong>{{ $tab==='dashboard'?$watchlist->count():'$'.number_format($cost,2) }}</strong></div></div>@endif
@if($tab==='dashboard')<div class="welcome-panel"><div><h2>A little research goes a long way.</h2><p>{{ auth()->user()->trial_ends_at?->isFuture()?'Your research trial ends '.auth()->user()->trial_ends_at->format('d M Y').'.':'Your trial has ended. Open-access research and your portfolio tools remain available.' }}</p></div><a class="button" href="{{ route('research') }}">Open the research desk ↗</a></div><h2>From the research desk</h2><div class="reports-grid">@foreach($reports as $report)<x-report-card :report="$report"/>@endforeach</div>@endif
@if($tab==='portfolio')<div class="panel"><h2>Add a holding</h2><form class="inline-form" method="post" action="{{ route('holding') }}">@csrf<label>Company<select name="stock_id">@foreach($stocks as $s)<option value="{{ $s->id }}">{{ $s->symbol }} · {{ $s->name }}</option>@endforeach</select></label><label>Quantity<input type="number" name="quantity" step="0.0001" min="0.0001" required></label><label>Average buy price (AUD)<input type="number" name="buy_price" step="0.0001" min="0.0001" required></label><button class="button">Add holding +</button></form></div><div class="table-scroll panel"><table><thead><tr><th>Company</th><th>Quantity</th><th>Buy price</th><th>Value</th><th>Gain / loss</th><th></th></tr></thead><tbody>@forelse($holdings as $h)<tr><td><a href="{{ route('stock',$h->symbol) }}"><b>{{ $h->symbol }}</b><small>{{ $h->name }}</small></a></td><td>{{ (float)$h->quantity }}</td><td>${{ number_format($h->buy_price,2) }}</td><td>${{ number_format($h->price*$h->quantity,2) }}</td><td class="{{ $h->price>=$h->buy_price?'positive':'negative' }}">${{ number_format(($h->price-$h->buy_price)*$h->quantity,2) }}</td><td><form method="post" action="{{ route('remove',['type'=>'holdings','id'=>$h->id]) }}">@csrf @method('DELETE')<button class="link-button danger">Remove</button></form></td></tr>@empty<tr><td colspan="6" class="empty-state">Your portfolio starts with your first holding. Add one above.</td></tr>@endforelse</tbody></table></div><p class="small-text muted">Unrealised gain/loss excludes dividends, fees and tax. Multiple purchases are recorded as separate lots.</p>@endif
@if($tab==='watchlist')<div class="panel"><h2>Add a company</h2><form class="inline-form" method="post" action="{{ route('watch') }}">@csrf<label>Company<select name="stock_id">@foreach($stocks as $s)<option value="{{ $s->id }}">{{ $s->symbol }} · {{ $s->name }}</option>@endforeach</select></label><label>Alert when price at or below (optional)<input type="number" name="alert_price" min="0.0001" step="0.0001" placeholder="AUD"></label><button class="button">Save to watchlist +</button></form><p class="small-text muted">Thresholds appear below using the demo price. Email and live-price alerts are not connected. Saving an existing company updates its threshold.</p></div><div class="table-scroll panel"><table><thead><tr><th>Company</th><th>Demo price</th><th>Change</th><th>Threshold status</th><th></th></tr></thead><tbody>@forelse($watchlist as $s)<tr><td><a href="{{ route('stock',$s->symbol) }}"><b>{{ $s->symbol }}</b><small>{{ $s->name }}</small></a></td><td>${{ number_format($s->price,2) }}</td><td>{{ $s->change }}%</td><td>{{ $s->alert_price ? ($s->price<=$s->alert_price?'Threshold reached':'Watching').' · $'.number_format($s->alert_price,2) : 'No price threshold' }}</td><td><form method="post" action="{{ route('remove',['type'=>'watchlists','id'=>$s->id]) }}">@csrf @method('DELETE')<button class="link-button danger">Remove</button></form></td></tr>@empty<tr><td colspan="5" class="empty-state">No companies yet. Add a company to start following it.</td></tr>@endforelse</tbody></table></div>@endif
@if($tab==='subscription')<div class="panel"><h2>{{ auth()->user()->trial_ends_at?->isFuture()?'Explorer trial':'Explorer' }}</h2><p>{{ auth()->user()->trial_ends_at?->isFuture()?'Premium research access until '.auth()->user()->trial_ends_at->format('d M Y'):'Open-access research and investor tools.' }}</p><a class="button" href="{{ route('page','pricing') }}">Explore membership plans ↗</a></div><h2>Plan requests</h2>@forelse($subscriptions as $sub)<div class="panel"><b>{{ $sub->plan }} · {{ ucfirst($sub->billing) }}</b><span class="tag">{{ ucfirst($sub->status) }}</span><p>No charge has been made. Paid checkout and activation are not connected in this demo.</p></div>@empty<div class="empty-state">You have no pending plan requests.</div>@endforelse @endif
</div></section>
@endsection
