@extends('layouts.app')
@section('title','Admin studio')
@section('content')
<section class="page-heading container"><span class="eyebrow">STOCKEDGE ADMIN STUDIO</span><h1>Your publishing desk.</h1><p>Manage research, editorial content and incoming enquiries.</p><a href="{{ route('dashboard') }}">← Member workspace</a></section><section class="container section compact">
<div class="metric-grid"><div class="metric"><small>Research reports</small><strong>{{ $reports->count() }}</strong></div><div class="metric"><small>Articles</small><strong>{{ $articles->count() }}</strong></div><div class="metric"><small>Enquiries</small><strong>{{ $leads->count() }}</strong></div><div class="metric"><small>Plan requests</small><strong>{{ $subscriptions->count() }}</strong></div></div>
@foreach(['report','article'] as $type)
<details class="admin-section"><summary><h2>{{ ucfirst($type) }} publishing</h2><span>+</span></summary>
@include('components.admin-form',['item'=>null,'type'=>$type])
@foreach($type==='report'?$reports:$articles as $item)<details class="admin-item"><summary>{{ $item->title }} <span class="tag">{{ $item->published?'Published':'Draft' }}</span></summary>@include('components.admin-form',['item'=>$item,'type'=>$type])<form method="post" data-confirm="Delete this content permanently?" action="{{ route('admin.delete',[$type,$item->id]) }}">@csrf @method('DELETE')<button class="link-button danger">Delete {{ $type }}</button></form></details>@endforeach</details>@endforeach
<h2>Enquiries & newsletter signups</h2><div class="panel table-scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Name / Email</th><th>Phone</th><th>Message</th><th>Consent</th></tr></thead><tbody>@forelse($leads as $lead)<tr><td>{{ $lead->created_at }}</td><td>{{ $lead->type }}</td><td>{{ $lead->name }}<small>{{ $lead->email }}</small></td><td>{{ $lead->phone }}</td><td>{{ $lead->message }}</td><td>{{ $lead->consent?'Yes':'No' }}</td></tr>@empty<tr><td colspan="6">No enquiries yet.</td></tr>@endforelse</tbody></table></div><h2>Membership requests</h2><div class="panel table-scroll"><table><thead><tr><th>Email</th><th>Plan</th><th>Billing</th><th>Status</th></tr></thead><tbody>@forelse($subscriptions as $sub)<tr><td>{{ $sub->email }}</td><td>{{ $sub->plan }}</td><td>{{ $sub->billing }}</td><td>{{ $sub->status }}</td></tr>@empty<tr><td colspan="4">No membership requests yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
