@extends('layouts.admin')
@section('title',($record?'Edit ':'New ').strtolower($definition['singular']))
@section('content')
<a class="a-back-link" href="{{ route('admin.records',$resource) }}">← {{ $definition['title'] }}</a>
<div class="a-page-heading"><div><div class="a-kicker">{{ $record?'RECORD #'.str_pad($record->id,4,'0',STR_PAD_LEFT):'NEW RECORD' }}</div><h1>{{ $record?'Edit':'Create' }} {{ strtolower($definition['singular']) }}.</h1><p>{{ $definition['description'] }}</p></div><div class="a-heading-actions"><span class="a-save-state" data-save-state>All changes saved</span><a class="a-button secondary" href="{{ route('admin.records',$resource) }}">Cancel</a><button class="a-button" type="submit" form="record-editor"><x-admin-icon name="check"/>Save {{ strtolower($definition['singular']) }}</button></div></div>
<div class="a-editor-layout"><div>
@if(in_array($resource,['leads','requests']) && $record)<section class="a-panel a-submission"><div class="a-panel-heading"><div><h2>Original {{ $resource==='leads'?'submission':'request' }}</h2><p>Read-only source details</p></div><span class="a-badge neutral">{{ $resource==='leads'?$record->type:$record->plan }}</span></div><dl>@if($resource==='leads')<div><dt>Contact</dt><dd>{{ $record->name ?: 'Name not provided' }}</dd></div><div><dt>Email</dt><dd>{{ $record->email }}</dd></div><div><dt>Phone</dt><dd>{{ $record->phone ?: 'Not provided' }}</dd></div><div><dt>Consent recorded</dt><dd>{{ $record->consent?'Yes':'No' }} · {{ $record->created_at }}</dd></div><div class="wide"><dt>Message</dt><dd class="a-preserve">{{ $record->message ?: 'No message supplied.' }}</dd></div>@else<div><dt>Member</dt><dd>{{ $member?->name }} · {{ $member?->email }}</dd></div><div><dt>Billing preference</dt><dd>{{ ucfirst($record->billing) }}</dd></div><div><dt>Submitted</dt><dd>{{ $record->created_at }}</dd></div><div><dt>Payment</dt><dd>Not collected</dd></div>@endif</dl></section>@endif
<form id="record-editor" class="a-record-form" data-dirty-form method="post" action="{{ $record?route('admin.update',[$resource,$record->id]):route('admin.store',$resource) }}">@csrf @if($record)@method('PUT')<input type="hidden" name="_version" value="{{ old('_version',$record->updated_at) }}">@endif
@foreach(collect($definition['fields'])->groupBy('group',preserveKeys:true) as $group=>$fields)<section class="a-panel a-field-panel"><div class="a-panel-heading"><div><h2>{{ $group }}</h2></div><span class="a-step">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span></div><div class="a-field-grid">@foreach($fields as $field=>$spec)
@php($value=old($field,$record?->$field ?? ($field==='position'?10:($field==='item_limit'?4:($field==='is_active'?1:'')))))
@php($required=is_string($spec['rules'])?str_contains($spec['rules'],'required'):in_array('required',$spec['rules'],true))
@if($spec['type']==='checkbox')<div class="a-field a-checkbox-field"><input type="hidden" name="{{ $field }}" value="0"><label class="a-switch-row" for="field-{{ $field }}"><span><b>{{ $spec['label'] }}</b>@if($spec['hint'])<small>{{ $spec['hint'] }}</small>@endif</span><input type="checkbox" id="field-{{ $field }}" name="{{ $field }}" value="1" @checked($value)><span class="a-switch" aria-hidden="true"></span></label></div>
@else<div @class(['a-field','wide'=>in_array($spec['type'],['textarea','editor'])])><label for="field-{{ $field }}">{{ $spec['label'] }} @if($required)<span class="a-required">*</span>@else<span class="a-optional">Optional</span>@endif</label>
@if(in_array($spec['type'],['select','media']))<select id="field-{{ $field }}" name="{{ $field }}" @required($required) @if($spec['hint'])aria-describedby="hint-{{ $field }}"@endif><option value="">{{ $required?'Select an option':'None selected' }}</option>@foreach($spec['options'] as $option=>$label)<option value="{{ $option }}" @selected((string)$value===(string)$option)>{{ $label }}</option>@endforeach</select>@if($spec['type']==='media')<a class="a-field-link" href="{{ route('admin.media') }}" target="_blank" rel="noopener">Open media library <x-admin-icon name="external"/></a>@endif
@elseif(in_array($spec['type'],['textarea','editor']))<textarea id="field-{{ $field }}" name="{{ $field }}" rows="{{ $spec['type']==='editor'?12:3 }}" @required($required) data-character-count @if($spec['hint'])aria-describedby="hint-{{ $field }}"@endif>{{ $value }}</textarea><span class="a-character-count"></span>
@else
@php($inputType=match($spec['type']){'slug','url'=>'text','integer'=>'number',default=>$spec['type']})
@php($displayValue=$spec['type']==='password'?'':($spec['type']==='datetime-local' && $value?\Illuminate\Support\Carbon::parse($value)->format('Y-m-d\TH:i'):$value))
<input id="field-{{ $field }}" name="{{ $field }}" type="{{ $inputType }}" value="{{ $displayValue }}" @required($required || ($resource==='members' && !$record && $field==='password')) @if($spec['type']==='password')autocomplete="new-password"@endif @if($inputType==='number')step="{{ $spec['type']==='integer'?'1':'0.0001' }}"@endif @if($field==='slug')data-slug-field @endif @if($field==='title')data-title-field @endif @if($record && $resource==='pages' && $record->system && $field==='slug')readonly @endif @if($spec['hint'])aria-describedby="hint-{{ $field }}"@endif>
@endif
@if($spec['hint'])<p class="a-field-hint" id="hint-{{ $field }}">{{ $spec['hint'] }}</p>@endif
@error($field)<p class="a-field-error">{{ $message }}</p>@enderror
</div>@endif @endforeach</div></section>@endforeach
<div class="a-editor-bottom"><span><x-admin-icon name="shield"/>Saved changes are recorded in the activity log.</span><button class="a-button" type="submit">Save {{ strtolower($definition['singular']) }} <x-admin-icon name="check"/></button></div></form>
</div><aside class="a-editor-aside"><section class="a-panel"><div class="a-panel-heading"><h2>Record details</h2><x-admin-icon name="reports"/></div><div class="a-record-meta"><dl><div><dt>Type</dt><dd>{{ $definition['singular'] }}</dd></div><div><dt>Record ID</dt><dd>{{ $record?'#'.str_pad($record->id,4,'0',STR_PAD_LEFT):'Assigned on save' }}</dd></div><div><dt>Created</dt><dd>{{ $record?\Illuminate\Support\Carbon::parse($record->created_at)->format('d M Y, H:i'):'Not saved yet' }}</dd></div><div><dt>Last changed</dt><dd>{{ $record?\Illuminate\Support\Carbon::parse($record->updated_at)->format('d M Y, H:i'):'Not saved yet' }}</dd></div></dl>
@if($record && ($publicUrl=\App\Support\AdminResources::publicUrl($resource,$record)))<a class="a-button secondary full" href="{{ $publicUrl }}" target="_blank" rel="noopener">Open website location <x-admin-icon name="external"/></a><p class="a-field-hint">Published records are visible publicly. Draft reports and pages return a not-found response.</p>@endif</div></section>
@if(in_array($resource,['reports','articles','pages']))<section class="a-notebook"><span class="a-kicker">BEFORE YOU PUBLISH</span><h3>A useful editorial check.</h3><ul><li>Is the title specific to the subject?</li><li>Are the claims supported and the risks clear?</li><li>Is the collection and access level correct?</li><li>Have you checked the public page?</li></ul><button class="a-button secondary full" type="button" data-preview-button>Preview body structure</button></section>@endif
@if($resource==='sections')<section class="a-notebook"><span class="a-kicker">COMPOSITION NOTES</span><h3>Give each section a job.</h3><p>Use one clear headline and a destination that follows from it. Research and editorial layouts draw from published records; changing the limit does not create content.</p><p>Only text layouts display the optional image. New application features require development.</p></section>@endif
@if($history->count())<section class="a-panel"><div class="a-panel-heading"><h2>Change history</h2></div><div class="a-mini-history">@foreach($history as $event)<div><b>{{ ucfirst($event->action) }} by {{ $event->actor }}</b><small>{{ \Illuminate\Support\Carbon::parse($event->created_at)->format('d M Y, H:i') }}</small><p>{{ implode(', ',json_decode($event->changed_fields,true)??[]) }}</p></div>@endforeach</div></section>@endif
@if($record && $definition['delete'])<section class="a-delete-zone"><h3>Delete record</h3><p>{{ $resource==='pages' && $record->system?'System pages are protected from deletion.':'This removes the record permanently. Linked company records are protected.' }}</p>@unless($resource==='pages' && $record->system)<form method="post" action="{{ route('admin.destroy',[$resource,$record->id]) }}" data-delete-form>@csrf @method('DELETE')<input type="hidden" name="_version" value="{{ $record->updated_at }}"><button class="a-button danger-outline full">Delete {{ strtolower($definition['singular']) }}</button></form>@endunless</section>@endif
</aside></div>
<dialog class="a-dialog a-preview-dialog" id="body-preview"><form method="dialog"><div class="a-panel-heading"><h2>Body structure preview</h2><button class="a-icon-button" aria-label="Close preview">×</button></div></form><p class="a-field-hint">Unsaved text preview. The public page supplies the final typography and surrounding layout.</p><div data-preview-content></div></dialog>
@endsection