@extends('layouts.admin')
@section('title',$definition['title'])
@section('content')
<div class="a-page-heading"><div><div class="a-kicker">{{ $resource==='sections'?'WEBSITE COMPOSITION':'CONTENT & OPERATIONS' }}</div><h1>{{ $definition['title'] }}<span class="a-heading-count">{{ $counts['total'] }}</span></h1><p>{{ $definition['description'] }}</p></div>@if($definition['create'])<a class="a-button" href="{{ route('admin.create',$resource) }}"><x-admin-icon name="plus"/>Add {{ strtolower($definition['singular']) }}</a>@endif</div>
@if($resource==='sections')<div class="a-info-strip"><x-admin-icon name="sections"/><div><b>The order below is the order on your website.</b><span>Use Move up / Move down to reorder. Hidden sections remain editable. Add new sections from eight supported layouts.</span></div><a href="{{ route('home') }}" target="_blank" rel="noopener">View homepage <x-admin-icon name="external"/></a></div>@endif
<div class="a-panel"><div class="a-library-tabs"><a @class(['active'=>!request()->filled('status')]) href="{{ route('admin.records',$resource) }}">All records <b>{{ $counts['total'] }}</b></a>@if(isset($counts['published']))<a @class(['active'=>request('status')==='1']) href="{{ route('admin.records',['resource'=>$resource,'status'=>1]) }}">Published <b>{{ $counts['published'] }}</b></a><a @class(['active'=>request('status')==='0']) href="{{ route('admin.records',['resource'=>$resource,'status'=>0]) }}">Draft / hidden <b>{{ $counts['drafts'] }}</b></a>@endif</div>
<form class="a-filter-bar" method="get"><div class="a-search"><x-admin-icon name="search"/><label class="a-sr-only" for="record-search">Search {{ $definition['title'] }}</label><input id="record-search" name="q" value="{{ request('q') }}" placeholder="Search {{ strtolower($definition['title']) }}…" maxlength="100"></div>
@if($definition['status'])<label class="a-sr-only" for="status-filter">Filter status</label><select name="status" id="status-filter"><option value="">All statuses</option>@php($statusOptions=match($definition['status']){'published'=>['1'=>'Published','0'=>'Draft / hidden'],'is_active'=>['1'=>'Active','0'=>'Suspended'],default=>$definition['fields']['status']['options']})@foreach($statusOptions as $value=>$label)<option value="{{ $value }}" @selected((string)request('status')===(string)$value)>{{ $label }}</option>@endforeach</select>@endif
<label class="a-sr-only" for="sort-filter">Sort records</label><select name="sort" id="sort-filter"><option value="updated">Recently updated</option><option value="oldest" @selected(request('sort')==='oldest')>Oldest first</option><option value="name" @selected(request('sort')==='name')>Name A–Z</option></select><button class="a-button secondary">Apply</button>@if(request()->hasAny(['q','status','sort']))<a class="a-reset" href="{{ route('admin.records',$resource) }}">Reset</a>@endif</form>
<div class="a-table-scroll"><table class="a-table"><thead><tr><th class="a-row-number">#</th>@foreach($definition['columns'] as $label)<th>{{ strtoupper($label) }}</th>@endforeach<th>UPDATED</th><th class="a-align-right">ACTIONS</th></tr></thead><tbody>@forelse($records as $record)<tr><td class="a-row-number">{{ str_pad($record->id,2,'0',STR_PAD_LEFT) }}</td>@foreach($definition['columns'] as $field=>$label)<td>@if($loop->first)<a class="a-record-title" href="{{ route('admin.edit',[$resource,$record->id]) }}">{{ \Illuminate\Support\Str::limit((string)$record->$field,90) }}</a>@if(isset($record->slug))<small>/{{ $resource==='reports'?'reports/':($resource==='articles'?'insights/':'') }}{{ $record->slug }}</small>@endif
@elseif(in_array($field,['published','is_active','is_admin','premium','featured','show_in_footer','consent']))@php($labels=match($field){'published'=>['Draft','Published'],'is_active'=>['Suspended','Active'],'is_admin'=>['Member','Admin'],'premium'=>['Open','Members'],'consent'=>['Not given','Given'],default=>['No','Yes']})<span class="a-badge {{ $record->$field?'green':'neutral' }}">{{ $labels[(int)(bool)$record->$field] }}</span>
@elseif($field==='status')<span class="a-badge {{ in_array($record->$field,['new','pending'])?'amber':'neutral' }}">{{ ucfirst(str_replace('_',' ',$record->$field)) }}</span>
@elseif(in_array($field,['price','monthly_price','yearly_price']))<span class="a-mono">${{ number_format($record->$field,2) }}</span>
@elseif($field==='rating')<span class="a-badge {{ $record->$field==='Buy'?'green':($record->$field==='Sell'?'red':'amber') }}">{{ $record->$field }}</span>
@elseif($field==='trial_ends_at')<span class="a-date-cell">{{ $record->$field ? \Illuminate\Support\Carbon::parse($record->$field)->format('d M Y') : 'No trial' }}</span>
@else{{ $record->$field }}@endif</td>@endforeach<td class="a-date-cell">{{ \Illuminate\Support\Carbon::parse($record->updated_at)->format('d M Y') }}<small>{{ \Illuminate\Support\Carbon::parse($record->updated_at)->format('H:i') }}</small></td><td><div class="a-row-actions">@if($resource==='sections')@foreach(['up'=>'↑','down'=>'↓'] as $direction=>$symbol)<form method="post" action="{{ route('admin.reorder',$record->id) }}">@csrf<input type="hidden" name="direction" value="{{ $direction }}"><button class="a-icon-button" title="Move {{ $direction }}" aria-label="Move {{ $record->name }} {{ $direction }}">{{ $symbol }}</button></form>@endforeach @endif<a class="a-edit-link" href="{{ route('admin.edit',[$resource,$record->id]) }}">Edit <x-admin-icon name="arrow"/></a></div></td></tr>@empty<tr><td colspan="{{ count($definition['columns'])+3 }}"><div class="a-empty"><x-admin-icon :name="$resource"/><h3>{{ request('q')?'No records match your search.':'Nothing here yet.' }}</h3><p>{{ request('q')?'Try a different phrase or clear the filters.':'New records will appear here as you build your workspace.' }}</p>@if($definition['create'])<a href="{{ route('admin.create',$resource) }}">Add {{ strtolower($definition['singular']) }}</a>@endif</div></td></tr>@endforelse</tbody></table></div><div class="a-pagination"><span>{{ $records->total() ? $records->firstItem().'–'.$records->lastItem() : '0' }} of {{ $records->total() }} records</span><div>@if($records->previousPageUrl())<a href="{{ $records->previousPageUrl() }}">← Previous</a>@endif<span>Page {{ $records->currentPage() }}</span>@if($records->nextPageUrl())<a href="{{ $records->nextPageUrl() }}">Next →</a>@endif</div></div></div>
@endsection