@extends('layouts.sales')
@section('title','Lead journey')
@section('content')
<a class="a-back-link" href="{{ route('sales.dashboard') }}">← Back to lead pipeline</a>
<div class="a-page-heading"><div><div class="a-kicker">LEAD #{{ str_pad($lead->id,4,'0',STR_PAD_LEFT) }}</div><h1>{{ $lead->name ?: $lead->email }}</h1><p>{{ $lead->email }}@if($lead->phone) · {{ $lead->phone }}@endif · {{ ucfirst($lead->type) }} enquiry</p></div><div class="a-heading-actions">@if($lead->phone)<a class="a-button secondary" href="tel:{{ preg_replace('/[^+0-9]/','',$lead->phone) }}"><x-admin-icon name="phone"/>Start call</a>@endif @if(!$lead->contact_id)<form method="post" action="{{ route('sales.leads.convert',$lead) }}">@csrf<button class="a-button"><x-admin-icon name="check"/>Convert to customer</button></form>@else<a class="a-button" href="{{ route('sales.contacts.edit',$lead->contact_id) }}"><x-admin-icon name="members"/>Open customer</a>@endif</div></div>
<div class="crm-layout"><div>
<section class="a-panel a-field-panel"><div class="a-panel-heading"><div><h2>Lead details</h2><p>Assignment and pipeline status.</p></div><span class="a-badge {{ $lead->status==='converted'?'green':'neutral' }}"><i></i>{{ ucfirst($lead->status) }}</span></div><form method="post" action="{{ route('sales.leads.update',$lead) }}">@csrf @method('put')<div class="a-field-grid"><div class="a-field"><label for="lead-name">Name</label><input id="lead-name" name="name" value="{{ old('name',$lead->name) }}" maxlength="120"></div><div class="a-field"><label for="lead-email">Email</label><input id="lead-email" name="email" type="email" value="{{ old('email',$lead->email) }}" required></div><div class="a-field"><label for="lead-phone">Phone</label><input id="lead-phone" name="phone" value="{{ old('phone',$lead->phone) }}" maxlength="30"></div><div class="a-field"><label for="lead-status">Status</label><select id="lead-status" name="status" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status',$lead->status)===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="a-field wide"><label for="assigned-to">Owner</label><select id="assigned-to" name="assigned_to"><option value="">Unassigned</option>@foreach($salesUsers as $salesUser)<option value="{{ $salesUser->id }}" @selected((string)old('assigned_to',$lead->assigned_to)===(string)$salesUser->id)>{{ $salesUser->name }}</option>@endforeach</select></div></div><div class="crm-form-actions"><button class="a-button">Save lead</button></div></form></section>
<section class="a-panel"><div class="a-panel-heading"><div><h2>Lead journey</h2><p>A permanent timeline of the enquiry, responses and sales actions.</p></div></div><div class="crm-journey"><article><span class="a-timeline-dot"></span><div><b>Original {{ $lead->type }} enquiry</b><small>{{ $lead->created_at->format('d M Y, H:i') }}</small><p>{{ $lead->message ?: 'No message was supplied.' }}</p></div></article>@foreach($lead->activities as $activity)<article><span class="a-timeline-dot"></span><div><b>{{ ucfirst(str_replace('_',' ',$activity->type)) }}@if($activity->outcome) · {{ ucfirst(str_replace('_',' ',$activity->outcome)) }}@endif</b><small>{{ $activity->occurred_at->format('d M Y, H:i') }} · {{ $activity->user?->name ?? 'System' }}@if($activity->duration_seconds) · {{ gmdate('i:s',$activity->duration_seconds) }}@endif</small>@if($activity->details)<p>{{ $activity->details }}</p>@endif</div></article>@endforeach</div></section>
</div><aside>
@if($lead->phone)<section class="a-panel"><div class="a-panel-heading"><div><h2>Record a call</h2><p>Start the call on your device, then save the outcome.</p></div></div><form class="crm-side-form" method="post" action="{{ route('sales.leads.calls',$lead) }}">@csrf<a class="a-button full" href="tel:{{ preg_replace('/[^+0-9]/','',$lead->phone) }}"><x-admin-icon name="phone"/>Call {{ $lead->phone }}</a><div class="a-field"><label for="call-outcome">Outcome</label><select id="call-outcome" name="outcome" required><option value="answered">Answered</option><option value="voicemail">Voicemail</option><option value="no_answer">No answer</option><option value="busy">Busy</option><option value="wrong_number">Wrong number</option></select></div><div class="a-field"><label for="call-duration">Duration (seconds)</label><input id="call-duration" name="duration_seconds" type="number" min="0" max="86400"></div><div class="a-field"><label for="call-details">Response / notes</label><textarea id="call-details" name="details" rows="4" maxlength="5000"></textarea></div><button class="a-button secondary full">Save call outcome</button></form></section>@endif
<section class="a-panel"><div class="a-panel-heading"><div><h2>Add journey entry</h2><p>Record the lead’s response or your follow-up.</p></div></div><form class="crm-side-form" method="post" action="{{ route('sales.leads.journey',$lead) }}">@csrf<div class="a-field"><label for="journey-type">Entry type</label><select id="journey-type" name="type" required><option value="response">Lead response</option><option value="note">Internal note</option><option value="email">Email</option><option value="sms">SMS</option><option value="meeting">Meeting</option></select></div><div class="a-field"><label for="journey-details">Details</label><textarea id="journey-details" name="details" rows="6" required maxlength="5000"></textarea></div><button class="a-button full">Add to journey</button></form></section>
</aside></div>
@endsection
