<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>@yield('title','Overview') · SharesRise Admin</title><link rel="icon" href="{{ asset('favicon.svg') }}"><link rel="stylesheet" href="{{ asset('css/admin.css') }}"><script defer src="{{ asset('js/admin.js') }}"></script></head>
<body><a href="#workspace" class="a-skip">Skip to workspace</a>
<aside class="a-sidebar" id="admin-sidebar"><a class="a-brand" href="{{ route('admin') }}"><span class="a-brand-mark"><x-admin-icon name="external"/></span><span>SharesRise<small>ADMIN WORKSPACE</small></span></a><div class="a-workspace-label"><span class="a-status-dot"></span> Research & operations <span>01</span></div>
<nav aria-label="Administration"><a @class(['a-nav-link','active'=>request()->routeIs('admin')]) href="{{ route('admin') }}"><x-admin-icon name="grid"/>Overview</a>
@foreach(\App\Support\AdminResources::navigation() as $group=>$links)<div class="a-nav-group">{{ $group }}</div>@foreach($links as $key=>$label)<a @class(['a-nav-link','active'=>($resource??'')===$key || ($key==='media' && request()->routeIs('admin.media'))]) href="{{ $key==='media'?route('admin.media'):route('admin.records',$key) }}"><x-admin-icon :name="$key"/>{{ $label }}</a>@endforeach @endforeach
<div class="a-nav-group">Workspace</div><a @class(['a-nav-link','active'=>request()->routeIs('admin.activity')]) href="{{ route('admin.activity') }}"><x-admin-icon name="activity"/>Activity log</a><a @class(['a-nav-link','active'=>request()->routeIs('admin.settings')]) href="{{ route('admin.settings') }}"><x-admin-icon name="settings"/>Website settings</a></nav>
<div class="a-sidebar-bottom"><div class="a-environment"><x-admin-icon name="shield"/><div><b>Development workspace</b><span>Demo market data · Payments off</span></div></div><div class="a-user"><span class="a-avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><div><b>{{ auth()->user()->name }}</b><small>Administrator</small></div><form method="post" action="{{ route('logout') }}">@csrf<button title="Log out" aria-label="Log out"><x-admin-icon name="logout"/></button></form></div></div></aside>
<div class="a-shell"><header class="a-topbar"><div class="a-breadcrumb"><button class="a-menu-button" aria-controls="admin-sidebar" aria-expanded="false" aria-label="Toggle navigation"><x-admin-icon name="menu"/></button><span>Workspace</span><x-admin-icon name="chevron"/><strong>@yield('title','Overview')</strong></div><div class="a-topbar-actions"><span class="a-local-date">{{ now()->format('D, d M Y') }}</span><a href="{{ route('home') }}" target="_blank" rel="noopener">View website <x-admin-icon name="external"/></a></div></header>
<main id="workspace" class="a-main">@if(session('success'))<div class="a-flash" role="status"><x-admin-icon name="check"/><span>{{ session('success') }}</span><button type="button" data-dismiss aria-label="Dismiss message">×</button></div>@endif
@if(isset($errors) && $errors->any())<div class="a-flash a-flash-error" role="alert"><div><b>We couldn’t save that change.</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif
@yield('content')</main><footer class="a-footer"><span>SharesRise · Research operations</span><span>Changes are recorded in the activity log.</span></footer></div>
<dialog id="confirm-dialog" class="a-dialog"><form method="dialog"><span class="a-kicker">CONFIRM DELETION</span><h2>Delete this record?</h2><p data-confirm-description>This cannot be undone. Referenced records cannot be deleted.</p><div class="a-dialog-actions"><button class="a-button secondary" value="cancel">Keep record</button><button class="a-button danger" value="confirm">Delete record</button></div></form></dialog>
</body></html>