<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Independent market research') | StockEdge</title><meta name="description" content="Discover StockEdge: equity research, market insights and tools for a more considered investment approach."><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><link rel="stylesheet" href="{{ asset('css/app.css') }}"><script defer src="{{ asset('js/app.js') }}"></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<div class="announcement"><span><i class="dot"></i> A clearer perspective on the market.</span><a href="{{ route('page','free-report') }}">Explore your complimentary research report <span>↗</span></a></div>
<header class="site-header"><div class="container nav-row">
<a class="brand" href="{{ route('home') }}" aria-label="StockEdge home"><span class="brand-mark">↗</span>stock<span>edge</span><sup>®</sup></a>
<button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="navigation">☰</button>
<nav id="navigation" aria-label="Main navigation">
<details class="nav-dropdown"><summary>Research & reports <span>⌄</span></summary><div class="mega-menu"><div><small>RESEARCH COLLECTIONS</small>@foreach(config('stockedge.categories') as $category)<a href="{{ route('research',['category'=>$category]) }}">{{ $category }} <span>↗</span></a>@endforeach</div><div><small>EXPLORE THE MARKET</small><a href="{{ route('research') }}">All research →</a><a href="{{ route('page','sectors') }}">Sector insights</a>@foreach(['Blue Chip','Mid Cap','Small Cap'] as $cap)<a href="{{ route('research',['cap'=>$cap]) }}">{{ $cap }}</a>@endforeach<a href="{{ route('page','performance') }}">Track record</a></div></div></details>
<details class="nav-dropdown"><summary>Investor tools <span>⌄</span></summary><div class="small-menu"><a href="{{ route('account','portfolio') }}">Portfolio tracker</a><a href="{{ route('account','watchlist') }}">My watchlist</a><a href="{{ route('page','retirement') }}">Retirement planner</a></div></details>
<a href="{{ route('editorial') }}" @class(['active'=>request()->routeIs('editorial','article')])>Insights</a>
<a href="{{ route('page','pricing') }}">Pricing</a><a href="{{ route('page','about') }}">About us</a>
</nav>
<div class="nav-actions">@auth<a class="login-link" href="{{ route('dashboard') }}">My dashboard</a>@else<a class="login-link" href="{{ route('login') }}">Log in</a>@endauth<a class="button small" href="{{ route('register') }}">Get your edge <span>↗</span></a></div>
</div></header>
<div class="market-strip"><div class="container market-inner"><span class="market-label"><span class="dot"></span> MARKET SNAPSHOT <small>DEMO</small></span>@foreach([['ASX 200','8,246.20','+0.74%'],['ALL ORDS','8,489.60','+0.68%'],['S&P 500','5,634.61','+0.45%'],['GOLD','2,578.90','+1.12%']] as [$index,$price,$change])<div class="ticker"><span>{{ $index }}</span><b>{{ $price }}</b><em>↗ {{ $change }}</em></div>@endforeach</div></div>
<main id="main">@if(session('success'))<div class="container"><div class="notice" role="status">{{ session('success') }}</div></div>@endif
@if($errors->any())<div class="container"><div class="notice error" role="alert"><strong>Please check your details.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif
@yield('content')</main>
<section class="digest"><div class="container digest-inner"><div><span class="eyebrow">THE STOCKEDGE BRIEF</span><h2>A little insight. A bigger perspective.</h2><p>Make room for market stories that matter.</p></div><form method="post" action="{{ route('lead') }}">@csrf<input type="hidden" name="type" value="newsletter"><div class="email-row"><label class="sr-only" for="newsletter-email">Email address</label><input id="newsletter-email" name="email" type="email" placeholder="Enter your email address" required><button class="button" type="submit">Count me in ↗</button></div><label class="consent"><input type="checkbox" name="consent" value="1" required> I agree to receive the newsletter and accept the <a href="{{ route('page','privacy') }}">privacy policy</a>.</label></form></div></section>
<footer><div class="container"><div class="footer-grid"><div><a class="brand" href="{{ route('home') }}"><span class="brand-mark">↗</span>stock<span>edge</span></a><p>Independent thinking.<br>Informed investing.</p><span class="footer-note">An Australian market research platform.</span></div><div><h4>Explore</h4><a href="{{ route('research') }}">Research & reports</a><a href="{{ route('page','sectors') }}">Sector insights</a><a href="{{ route('editorial') }}">Market insights</a><a href="{{ route('page','performance') }}">Track record</a></div><div><h4>Your investing toolkit</h4><a href="{{ route('account','portfolio') }}">Portfolio tracker</a><a href="{{ route('account','watchlist') }}">Watchlist</a><a href="{{ route('page','retirement') }}">Retirement planning</a><a href="{{ route('page','pricing') }}">Membership plans</a></div><div><h4>Let’s connect</h4><a href="{{ route('page','about') }}">About StockEdge</a><a href="{{ route('page','contact') }}">Contact us ↗</a><a href="{{ route('page','free-report') }}">Get a free report</a>@can('admin')<a href="{{ route('admin') }}">Admin studio</a>@endcan</div></div><div class="disclaimer"><b>Demonstration website.</b> All market quotes, ratings, performance examples and editorial content are illustrative, not live data or investment advice. Investment values can fall as well as rise. No financial services licence or verified performance is claimed by this demo.</div><div class="footer-bottom"><span>© {{ date('Y') }} StockEdge. All rights reserved.</span><div>@foreach(['privacy'=>'Privacy policy','terms'=>'Terms of use','financial-services-guide'=>'Financial services guide','disclaimer'=>'Disclaimer'] as $path=>$label)<a href="{{ route('page',$path) }}">{{ $label }}</a>@endforeach</div><span>Made for a broader perspective ↗</span></div></div></footer>
</body></html>