<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>@yield('title','CRM') · SharesRise Sales</title><link rel="icon" href="{{ asset('images/sharesrise-logo-on-light.png') }}" type="image/png"><link rel="stylesheet" href="{{ asset('css/admin.css') }}"><script defer src="{{ asset('js/admin.js') }}"></script></head>
<body><a href="#workspace" class="a-skip">Skip to workspace</a>
<aside class="a-sidebar" id="admin-sidebar"><a class="a-brand" href="{{ route('sales.dashboard') }}" aria-label="SharesRise sales CRM"><img class="a-brand-logo" src="{{ asset('images/sharesrise-logo-on-dark.png') }}" alt="SharesRise" width="610" height="160"></a><div class="a-workspace-label"><span class="a-status-dot"></span> Sales CRM <span>LIVE</span></div>
<nav aria-label="Sales CRM"><div class="a-nav-group">Pipeline</div><a @class(['a-nav-link','active'=>request()->routeIs('sales.dashboard','sales.leads.*')]) href="{{ route('sales.dashboard') }}"><x-admin-icon name="leads"/>Leads</a><a @class(['a-nav-link','active'=>request()->routeIs('sales.contacts*')]) href="{{ route('sales.contacts') }}"><x-admin-icon name="members"/>Contacts</a>@if(auth()->user()->is_admin)<div class="a-nav-group">Workspace</div><a class="a-nav-link" href="{{ route('admin') }}"><x-admin-icon name="grid"/>Admin workspace</a>@endif</nav>
<div class="a-sidebar-bottom"><div class="a-environment"><x-admin-icon name="phone"/><div><b>Click-to-call ready</b><span>Uses your device dialler</span></div></div><div class="a-user"><span class="a-avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><div><b>{{ auth()->user()->name }}</b><small>{{ auth()->user()->is_admin?'Administrator':'Sales administrator' }}</small></div><form method="post" action="{{ route('logout') }}">@csrf<button title="Log out" aria-label="Log out"><x-admin-icon name="logout"/></button></form></div></div></aside>
<div class="a-shell"><header class="a-topbar"><div class="a-breadcrumb"><button class="a-menu-button" aria-controls="admin-sidebar" aria-expanded="false" aria-label="Toggle navigation"><x-admin-icon name="menu"/></button><span>Sales CRM</span><x-admin-icon name="chevron"/><strong>@yield('title','Pipeline')</strong></div><div class="a-topbar-actions"><span class="a-local-date">{{ now()->format('D, d M Y') }}</span><a href="{{ route('home') }}" target="_blank" rel="noopener">View website <x-admin-icon name="external"/></a></div></header>
<main id="workspace" class="a-main">@if(session('success'))<div class="a-flash" role="status"><x-admin-icon name="check"/><span>{{ session('success') }}</span><button type="button" data-dismiss aria-label="Dismiss message">×</button></div>@endif
@if($errors->any())<div class="a-flash a-flash-error" role="alert"><div><b>We couldn’t save that change.</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif
@yield('content')</main><footer class="a-footer"><span>SharesRise · Sales CRM</span><span>Lead responses and calls are recorded in the journey.</span></footer></div>
<dialog id="confirm-dialog" class="a-dialog"><form method="dialog"><span class="a-kicker">CONFIRM REMOVAL</span><h2>Remove this contact?</h2><p>This cannot be undone. The source lead and its journey will remain.</p><div class="a-dialog-actions"><button class="a-button secondary" value="cancel">Keep contact</button><button class="a-button danger" value="confirm">Remove contact</button></div></form></dialog>
</body></html>
